<script type="text/javascript">
	$(document).ready(function() {
		if ($('#answer').find('.errors').length == 0)
			$('#answer').find('form').hide();
		else
			$("#show-post").hide();
        $("#show-post").click(function() {
            $(this).hide();
        	$('#answer').find('form').toggle(400, function() {
        		$("#message-content").focus();
        	});
        });
        $("#go-answer").click(function() {
        	$("#show-post").click();
        });
	});
</script>
<div class="content-box">
<div class="top-left"></div>
<div class="top-right"></div>
<div id="title-message"></div>
<div id="messages-header">
	<div class="links"> 
		<a id="go-answer" href="#answer">R&eacute;pondre</a>
		/
		<?php echo $this->linkTag('Supprimer', array('controller' => 'message', 'action' => 'delete', 'id' => $this->thread->thread_id)); ?>
		/
		<?php echo $this->linkTag('Retour', array('controller' => 'message', 'action' => 'inbox', 'id' => null)); ?>
	</div>
	<div class="subject"><?php echo $this->escape($this->thread->subject); ?></div>
	<div class="clear"></div>
</div>
<div id="messages">

<?php foreach ($this->messages as $message) :?>
	<div class="msg-container <?php echo ($this->me == $message->user_id) ? "me" : "other"?>">
		<?php  echo $this->userImageTag($message->fbid, $message->miniature_id, 'jpg', 'mini'); ?>
		<div class="message">
			<span class="msg-info">
				<em>De: </em><span class="username"><?php echo $message->nickname?></span>
				- <em>le</em> <?php echo date('d/m/y', strtotime($message->date)); ?>
				<em>&agrave;</em> <?php echo date('H:i', strtotime($message->date)); ?>
			</span>
			<hr />
			<p><?php echo $this->escape($message->content); ?>
			</p>
			<div class="clear"></div>
		</div>
	</div>
<?php endforeach;?>
<div class="clear"></div>
<div class="msg-container me reponse">
<?php  echo $this->userImageTag($this->fbid, $this->photo, 'jpg', 'mini'); ?>
<!--<img src="<?php echo $this->baseUrl('images/thumbnail.png'); ?>" />-->
<div id="answer" class="message">
<span id="show-post">Repondre</span>
<?php
	echo $this->form;
?>
<div class="clear"></div>
</div>
</div>
<div class="clear"></div>
</div>
<div class="bottom-left"></div>
<div class="bottom-right"></div>
<div class="clear"></div>
</div>