<div>
		<h4>Bienvenu sur ImissU,</h4>
		<p>Tu n'es pas inscris sur ImissU, tu ne peux pas visiter cette page !</p>
		<p>Avec cette nouvelle application, tu vas pouvoir participer à des concours de photos.
		Envoie-nous vite tes plus jolies photos, récolte un maximum de vote et deviens la nouvelle idole de Facebook !</p>
		<?php echo $this->linkTag('Inscris toi !', array(
		'controller' => 'user', 'action' => 'subscribe'))?>
</div>