<div>
	<h4>Supprimer un utilisateur</h4>
	<ul>
	<?php foreach ($this->users as $user) : ?>
		<li><?php echo $user->user_id; ?> <?php echo $user->nickname; ?>
		<?php if ($user->is_activ)
				echo $this->linkTag('supprimer', array('controller' => 'admin', 'action' => 'del', 'id' => $user->user_id));
			else
				echo $this->linkTag('ré-activer', array('controller' => 'admin', 'action' => 'activ', 'id' => $user->user_id));
		 ?>
		</li>
	<?php endforeach; ?>
	</ul>
	<?php echo $this->LinkTag ('Retour', 
	array('controller' => 'admin', 'action' => 'index')); ?>
	
</div>
		